### ISSUE TITLE
Change the project name to lem-project.github.io

### ISSUE THREAD

**Issue by daninus14** [lem-project/lem-project.github.io#29]
The name of this repository should be lem-project.github.io (see https://pages.github.com/) so that the url becomes https://lem-project.github.io/ instead of https://lem-project.github.io/lem-page/ which for some reason browsers don't suggest and instead they suggest the former version.

You can just change it in the repository settings in the first page, first field...

**Comment by Sasanidas** [comment]
Seems like a very good idea indeed, ping @cxxxr to change the repository name (I don't have permission to do it) :+1:

**Comment by daninus14** [comment]
I take it mentioning him @cxxxr is enough 😉, thanks

**Comment by cxxxr** [comment]
Thanks for letting me know.
I changed it.
Some images and such no longer load, so this needs to be fixed.

**Comment by Sasanidas** [comment]
I changed the default URL and fixed the broken links :+1:

**Comment by Sasanidas** [comment]
I think we have also to change the URL on the lem-project description (ping @cxxxr )

**Comment by cxxxr** [comment]
@daninus14 
Has this issue been resolved?

**Comment by daninus14** [comment]
Yeah, thank you! I would've loved to be able to contribute to it myself, but it needed admin permissions on the project. Thanks for the lem project as well!
